name: Create/Update Kafka Topics Dev

on:
  push:
    branches:
      - 'dev-*'
    paths:
      - 'nais/topics.yml'

jobs:
  deploy-kafka-topics-dev:
    name: Deploy to Aiven Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          RESOURCE: nais/topics.yml